export const config = {
    data: "./data",
    template: {
        resume: "./templates/resume-template.html",
        careerHistory: "./templates/career-history-template.html"
    },
    out: {
        location: "./out",
        resumeFileName: "resume",
        careerHistoryFileName: "career-history",
        withDate: true
    },
    font: {
        serif: {
            name: "Noto Serif JP",
            file: "./fonts/NotoSerifJP-VariableFont_wght.ttf"
        },
        sansSerif: {
            name: "Noto Sans JP",
            file: "./fonts/NotoSansJP-VariableFont_wght.ttf"
        },
        monospace: {
            name: "Noto Sans Mono",
            file: "./fonts/NotoSansMono-VariableFont_wdth,wght.ttf"
        }
    },
    pdf: {
        // A4
        width: "210mm",
        height: "297mm",
        margin: {
            top: "10mm",
            right: "10mm",
            bottom: "10mm",
            left: "10mm"
        },
        preferCSSPageSize: true,
        printBackground: true,
        resume: {
            displayHeaderFooter: false,
        },
        careerHistory: {
            margin: {
                top: "10mm",
                right: "10mm",
                bottom: "25mm",
                left: "10mm"
            },
            displayHeaderFooter: true,
            headerTemplate: "<div></div>",
            footerTemplate: `
                <div style="position: relative; width: 100%; padding: 0 10mm 10mm; font-size: 9px; color: #000;">
                    <div style="position: relative; width: 100%; padding: 5px 0; border-top: solid 1px #ccc;">
                        <div style="position: absolute; left: 5px; top: 5px;">
                            <span>Generated by </span><a href="https://github.com/yo1000/resume-generator">resume-generator</a>
                        </div>
                        <div style="position: absolute; right: 5px; top: 5px;">
                            <span class="pageNumber"></span>/<span class="totalPages"></span>
                        </div>
                    </div>
                </div>
            `
        }
    },
    debug: false
};
