[profile]
name = "Familyname　Givenname"
career_summary = """
Career Summary

career summary
CAREER SUMMARY

aaaaaaaaaa bbbbbbbbbb
AAAAAAAAAA BBBBBBBBBB

cccccccccc dddddddddd
CCCCCCCCCC DDDDDDDDDD
"""

[[profile.skills]]
caption = "Caption"
items = ["Item1", "Item2", "Item3"]

[[profile.skills]]
caption = "caption"
items = ["item1", "item2", "item3"]

[[profile.skills]]
caption = "CAPTION"
items = ["ITEM1", "ITEM2", "ITEM3"]

[[profile.links]]
text = "Link Text"
url = "https://url.example.com"

[[profile.links]]
url = "https://url-only.example.com"

[[career_histories]]
company = "Career Histories"
term = "Term - Term"
summary = """
Summary Summary

summary summary
SUMMARY SUMMARY
"""

[[career_histories.works]]
name = "Works Name"
term = "Term - Term"
role = "Role"
responsibilities = ["Resp", "Onsi", "Bili", "Ties"]
stacks = ["Stack1", "Stack2"]
desc = """
Desc

desc
DESC
"""

[[career_histories.works]]
name = "works name"
term = "term - term"
role = "role"
responsibilities = ["resp", "onsi", "bili", "ties"]
stacks = ["stack1", "stack2"]
desc = """
Aaaa Bbbb Cccc Dddd

aaaa bbbb cccc dddd
AAAA BBBB CCCC DDDD
"""

[[career_histories]]
company = "career histories"
term = "term - term"
summary = "summary"

[[career_histories.works]]
name = "works name"
term = "term - term"
role = "role"
responsibilities = []
stacks = []
desc = ""

[promotion]
desc = """
Promotion Desc Promotion Desc Promotion Desc Promotion Desc Promotion Desc

promotion desc promotion desc promotion desc promotion desc promotion desc
PROMOTION DESC PROMOTION DESC PROMOTION DESC PROMOTION DESC PROMOTION DESC

aaaaaaaaaa bbbbbbbbbb cccccccccc dddddddddd eeeeeeeeee ffffffffff
gggggggggg hhhhhhhhhh iiiiiiiiii jjjjjjjjjj kkkkkkkkkk llllllllll
mmmmmmmmmm nnnnnnnnnn oooooooooo pppppppppp qqqqqqqqqq rrrrrrrrrr
ssssssssss tttttttttt uuuuuuuuuu vvvvvvvvvv wwwwwwwwww xxxxxxxxxx
yyyyyyyyyy zzzzzzzzzz

AAAAAAAAAA BBBBBBBBBB CCCCCCCCCC DDDDDDDDDD EEEEEEEEEE FFFFFFFFFF
GGGGGGGGGG HHHHHHHHHH IIIIIIIIII JJJJJJJJJJ KKKKKKKKKK LLLLLLLLLL
MMMMMMMMMM NNNNNNNNNN OOOOOOOOOO PPPPPPPPPP QQQQQQQQQQ RRRRRRRRRR
SSSSSSSSSS TTTTTTTTTT UUUUUUUUUU VVVVVVVVVV WWWWWWWWWW XXXXXXXXXX
YYYYYYYYYY ZZZZZZZZZZ
"""
